name: Pre-commit CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          pip install pre-commit gitlint

      - name: Run pre-commit (pre-commit stage only)
        run: pre-commit run --all-files --hook-stage pre-commit --show-diff-on-failure

      - name: Run gitlint on pushed commits
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE_REF="${{ github.event.pull_request.base.sha }}"
          else
            BASE_REF=$(git merge-base origin/main HEAD)
          fi

          echo "Linting commits from $BASE_REF to HEAD..."
          gitlint --commits "$BASE_REF..HEAD" --fail-without-commits
