name: Pre-commit CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          pip install pre-commit
          pre-commit install
          pre-commit install --hook-type commit-msg
          pre-commit install-hooks

      - name: Run pre-commit
        run: |
          git log -1 --pretty=%B > .git/COMMIT_EDITMSG
          pre-commit run --all-files --hook-stage pre-commit --show-diff-on-failure
          pre-commit run --hook-stage commit-msg --show-diff-on-failure --commit-msg-filename .git/COMMIT_EDITMSG
